version: '3'
services:
  web:
    build: .
    env_file: .env
    command: daphne mysign.asgi:application -b 0.0.0.0 --access-log - --verbosity 2
    restart: always
    depends_on:
      - db
    volumes:
      - ${PWD}/uploads:/app/uploads
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:${HOST}

  db:
    image: postgres:12
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis


  nginx:
    image: nginx
    restart: always
    volumes:
      - ${PWD}/static:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${HOST};PathPrefix:/static,/uploads

  traefik:
    image: traefik:1.7
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik.toml:/traefik.toml
      - ${PWD}/acme.json:/acme.json

volumes:
  postgres_data:
