version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DATABASE=test
      - POSTGRES_PASSWORD=test
  app:
    build: .
    depends_on:
      - db
    - environment:
        - POSTGRES_USER=test
        - POSTGRES_DATABASE=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_HOST=db
