version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - db
      - chromedriver
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  db:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"

  chromedriver:
    image: 'robcherry/docker-chromedriver'
    ports:
      - 4444:4444
    restart: on-failure
    shm_size: 1G
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=""