version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
    - "8000:8000"
    links:
    - db
  db:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"
volumes:
  logvolume01: {}