version: '3'
services:
  web:
    build: .
    env_file: .env
    command: gunicorn mysign.wsgi -b 0.0.0.0:8000
    restart: always
    depends_on:
      - db
      - chromedriver
    volumes:
      - ${PWD}/uploads:/app/uploads
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:utsign.nl

  db:
    image: postgres:12
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis


  nginx:
    image: nginx
    restart: always
    volumes:
      - ${PWD}/static:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:utsign.nl;PathPrefix:/static,/uploads

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik.toml:/traefik.toml
      - ${PWD}/acme.json:/acme.json

  chromedriver:
    image: blueimp/chromedriver
    tmpfs: /tmp
    restart: always
    environment:
      - DISABLE_X11=false
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    volumes:
      - ./assets:/home/webdriver/assets:ro
    ports:
      - 127.0.0.1:5900:5900

volumes:
  postgres_data:
