version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - db
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  db:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"
  chromedriver:
    image: blueimp/chromedriver
    tmpfs: /tmp
    environment:
      - DISABLE_X11=false
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    volumes:
      - ./assets:/home/webdriver/assets:ro
    ports:
      - 127.0.0.1:5900:5900