version: '3'
services:
  web:
    build: .
    env_file: .env
    command: gunicorn mysign.wsgi -b 0.0.0.0:8000
    restart: always
    depends_on:
      - db
      - chromedriver
    volumes:
      - ${PWD}/uploads:/app/uploads
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:utsign.nl

  db:
    image: postgres:12
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis


  nginx:
    image: nginx
    restart: always
    volumes:
      - ${PWD}/static:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:utsign.nl;PathPrefix:/static,/uploads

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik.toml:/traefik.toml
      - ${PWD}/acme.json:/acme.json

  chromedriver:
    image: 'robcherry/docker-chromedriver'
    ports:
      - 4444:4444
    restart: on-failure
    shm_size: 1G
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=""

volumes:
  postgres_data:
