steps:
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":pytest: Test"
    command: ["sh .buildkite/wait-for-it.sh", "db:5432", '--', 'pytest']
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":eslint: eslint"
    command: sh .buildkite/eslint.sh
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":lint-roller: Python linter"
    command: "flake8 ."
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":python: HTML linter"
    command: "pip3 install jinjalint attrs==17.2.0 && jinjalint mysign_app"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":python: Django check"
    command: "python3 manage.py check"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":docker: Deploy"
    command: .buildkite/deploy.sh
    branches: "development"
