steps:
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":lint: Linter"
    command: "flake8 ."
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":pytest: Test"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml
          command: ["./.buildkite/wait-for-it.sh", "db:5432", '--', 'pytest']
          env:
            - POSTGRES_HOST=db