steps:
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":lint-roller: Flake8"
    command: "flake8 ."
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":eslint: eslint"
    command: npm install -g eslint && eslint mysign_app
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":pytest: Test"
    command: ["sh .buildkite/wait-for-it.sh", "db:5432", '--', 'pytest']
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml
