# Generated by Django 2.2.5 on 2019-10-03 13:11

from django.db import migrations
import django_use_email_as_username.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysign_app', '0004_auto_20191002_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django_use_email_as_username.models.BaseUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
