# Generated by Django 2.2.5 on 2019-10-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysign_app', '0005_auto_20191003_1311'),
        ('mysign_app', '0005_auto_20191003_1300'),
    ]

    operations = [
    ]
