# Generated by Django 2.2.5 on 2019-10-10 15:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysign_app', '0006_auto_20191010_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='textcolor',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
    ]
