# Generated by Django 2.2.5 on 2019-10-11 11:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysign_app', '0007_company_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#e3eff3', max_length=18),
        ),
    ]
