# Generated by Django 2.2.5 on 2019-10-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysign_app', '0007_company_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This is not a valid domain name.', regex='(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]')]),
        ),
    ]
