# Generated by Django 2.2.5 on 2019-10-28 09:58

from django.db import migrations, models

import mysign_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysign_app', '0008_auto_20191011_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to=mysign_app.models.image_upload),
        ),
    ]
