# Generated by Django 2.2.5 on 2019-09-10 13:33

import callsign_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='DoorDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairing_code', models.CharField(default=callsign_app.models.generate_pairing_code, max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Pairing code should be 4 letters', regex='^\\w{4}$')])),
                ('pairing_code_expire_at', models.DateTimeField(default=callsign_app.models.expire_default)),
                ('secret', models.CharField(default=callsign_app.models.generate_secret, max_length=32)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign_app.Company')),
            ],
        ),
    ]
