# Generated by Django 2.2.5 on 2019-09-20 08:57

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mysign_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to=mysign_app.models.logo_upload)),
                ('color', colorfield.fields.ColorField(blank=True, max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='DoorDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=mysign_app.models.generate_secret, max_length=32)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysign_app.Company')),
            ],
        ),
    ]
